### ISSUE TITLE
程序出错

### ISSUE THREAD

**Issue by dhf2587154870** [ToryPan/ChatGPT_WeChat#7]
三行前面都删了空格还是老样子说我37行出错

**Comment by ToryPan** [comment]
提供一下截图呢

**Comment by dhf2587154870** [comment]
![Uploading 11.PNG…]()

**Comment by dhf2587154870** [comment]
![00](https://user-images.githubusercontent.com/92639256/233827341-7f102323-d4e8-4e9a-a50b-847fa9afe427.PNG)
把这个注释取消掉删掉3个#号 等于还要补一个空格？

**Comment by dhf2587154870** [comment]
![Uploading 11.PNG…]()

**Comment by dhf2587154870** [comment]
* Serving Flask app "myflask"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/bin/flask", line 11, in <module>
    load_entry_point('Flask==1.1.1', 'console_scripts', 'flask')()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 305, in __init__
    self._load_unlocked()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/root/ChatGPT_WeChat/myflask.py", line 37
    @app.route("/")

**Comment by ToryPan** [comment]
```
@app.route("/")
def hello():
    return "Hello test!"
```

你复制粘贴这个试试

**Comment by dhf2587154870** [comment]
> ```
> @app.route("/")
> def hello():
>     return "Hello test!"
> ```
> 
> 你复贴这个试试

可以了大佬 牛逼 但是语音识别不了

**Comment by dhf2587154870** [comment]
![44](https://user-images.githubusercontent.com/92639256/233827939-15071316-6ec0-406e-b8cd-b0cb5829d7b4.PNG)

**Comment by dhf2587154870** [comment]
![Uploading 阿迪王.PNG…]()
语音设置是从这儿填写密匙把

**Comment by ToryPan** [comment]
语音对话的话，你得看配置文件里面的：trans_to_voice是否为true，subscription和region是否设置正确，这个需要预先在azure上注册资源。还有微信公众号的接口设置里面，是否开启接受语音识别结果。
![image](https://user-images.githubusercontent.com/59463198/233828077-50af703c-2817-46a5-a5ec-8f88b570925d.png)

**Comment by dhf2587154870** [comment]
语音识别已经在微信公众平台开启了  那个azure上的密匙和区域也复制进去了 我给你截图看下对不对

**Comment by dhf2587154870** [comment]
speech_key, service_region这两个参数是在config.yml里面么

**Comment by ToryPan** [comment]
我猜你说的这两个参数是对应的subscription和region吧，因为配置文件里面没有speech_key, service_region，如果是的话，就在config.yml里面
